version: '3.8'
services:
  app:
    build: .
    ports:
      - "8001:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME_PRODUCTION: ${DB_NAME_PRODUCTION}
    depends_on:
      - db
    volumes:
      - ".:/rails"

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_PRODUCTION}
    volumes:
      - "db_data:/var/lib/postgresql/data"

volumes:
  db_data:

