default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Use environment variables for the host and port
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  # Ensure SSL is used if connecting to a production database in AWS
  sslmode: <%= ENV.fetch("DB_SSLMODE", "prefer") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT", "profile_service_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST", "profile_service_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION", "profile_service_production") %>